---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: jmx-buildpack

outputs:
- name: artifactory

caches:
- path: go-module-cache

run:
  path: jmx-buildpack/ci/package.sh
